### PR TITLE
rocksdb c wrapper

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Now if we need using a RocksDB feature but the C API is missing, we must add the C API first and wait RocksDB team to merge it, but we still have to wait the next stable RocksDB version released and then, we can use this feature. 
ref https://github.com/pingcap/tikv/issues/1432

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@siddontang @BusyJay PTAL

**Comment by zhangjinpeng1987** [comment]
PING

**Comment by zhangjinpeng1987** [comment]
@disksing

**Comment by disksing** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

PTAL @BusyJay

**Pull request merged**
