### PR TITLE
travis: use nightly only to pass CI.

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut @BusyJay @zhangjinpeng1987

### CODE REVIEW

**Comment by siddontang** [comment]
@BusyJay 
We still need to support stable rust later.

**Comment by BusyJay** [comment]
Can it pass 1.12?

**Comment by siddontang** [comment]
No, only nightly can pass.

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @BusyJay @zhangjinpeng1987

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
