### PR TITLE
upgrade rocksdb to 5.0.fb

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
upgrade rocksdb to 5.0.fb

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
Is this release stable enough?

**Comment by zhangjinpeng1987** [comment]
Rate limiter need update to 5.0.

**Comment by BusyJay** [comment]
Yes, but will it introduce potential bugs?

**Comment by zhangjinpeng1987** [comment]
Wait this release more stable.

**Pull request closed without merging**
