### PR TITLE
Add support for compaction_readahead_size

### PR DESCRIPTION
**Pull request by mrmiywj**
Add support for compaction_readahead_size
https://github.com/pingcap/tikv/issues/1507

### CODE REVIEW

**Comment by mrmiywj** [comment]
PTAL @siddontang @zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
Please add some tests.

**Comment by mrmiywj** [comment]
PTAL @zhangjinpeng1987

**Comment by siddontang** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
LGTM

**Pull request merged**
