### PR TITLE
src: add set_level_zero_file_num_compaction_trigger api

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
add set_level_zero_file_num_compaction_trigger api

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@ngaut @siddontang @BusyJay @disksing PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
@ngaut @BusyJay @disksing PTAL

**Comment by zhangjinpeng1987** [comment]
Tunning lock cf need this pr.

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
